model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autounet_a.AutoUNet_A
  params:
    monitor: "val/rec_loss"
    ckpt_path: "models/first_stage_models/kl-f8/model.ckpt"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.autounetloss.AutoUNetLoss
      params:
        w_shortcut: 1.0
        w_fusion: 1.0
        w_fusion_pix: 0.0
        w_fusion_lpips: 1.0

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 6
    train:
      target: ldm.data.openimage.FusionOpenImagePairDataset
      params:
        path: DATASET/openimage_pair_a
        split: train
        resize_res: 512
        size_crop: 128
    validation:
      target: ldm.data.openimage.FusionOpenImagePairDataset
      params:
        path: DATASET/openimage_pair_a
        split: val
        resize_res: 512
        size_crop: 128

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2

