model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autounet_b.AutoUNet_B
  params:
    target: fusion
    monitor: "val/rec_loss"
    ckpt_path: "models/first_stage_models/kl-f8/model.ckpt"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminatorNoKL
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    train:
      target: ldm.data.openimage_a.OpenImageTripleDataset
      params:
        path_gt: DATASET/openimage/gt512x512
        path_in: DATASET/openimage/nafnet_blur31/train
        path_z: DATASET/openimage/I_feat/blur31/train
        path_idx: indices/nafnet_blur31_feat_train.txt
        resize_res: 512
        size_crop: 512
    validation:
      target: ldm.data.openimage_a.OpenImageTripleDataset
      params:
        path_gt: DATASET/openimage/gt512x512
        path_in: DATASET/openimage/nafnet_blur31/valid
        path_z: DATASET/openimage/I_feat/blur31/valid
        path_idx: indices/nafnet_blur31_feat_valid.txt
        resize_res: 512
        size_crop: 512

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2

